name: rennda_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_core_web: ^2.9.0
  js: ^0.6.7
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  firebase_storage: ^11.6.5
  http: ^0.13.6  # ← ★追加：Cloud Functions呼び出し用
  badges: ^3.1.1 # ← ★追加：通知バッジ表示に必要
  intl: ^0.20.2
  cloud_functions: ^4.6.5  # ← ✅ 今回追加

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
