// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1f2iq1IrKPmuua6vW0QVRlsK29Kg2jc',
    appId: '1:217418164159:web:0caeca9ba9e7a3f608630a',
    messagingSenderId: '217418164159',
    projectId: 'quad-2c91f',
    authDomain: 'quad-2c91f.firebaseapp.com',
    storageBucket: 'quad-2c91f.firebasestorage.app',
    measurementId: 'G-HB1J4761B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJ6l_RgRDfkzbpAGa_sXcQ4Pxu2mrOt8',
    appId: '1:217418164159:android:204c00ded811e4c608630a',
    messagingSenderId: '217418164159',
    projectId: 'quad-2c91f',
    storageBucket: 'quad-2c91f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNfbpwX1Tyuz9mQqNWcTWC3431JtBJrhw',
    appId: '1:217418164159:ios:ba252ae5638e3ca708630a',
    messagingSenderId: '217418164159',
    projectId: 'quad-2c91f',
    storageBucket: 'quad-2c91f.firebasestorage.app',
    iosBundleId: 'com.example.renndaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNfbpwX1Tyuz9mQqNWcTWC3431JtBJrhw',
    appId: '1:217418164159:ios:ba252ae5638e3ca708630a',
    messagingSenderId: '217418164159',
    projectId: 'quad-2c91f',
    storageBucket: 'quad-2c91f.firebasestorage.app',
    iosBundleId: 'com.example.renndaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR1f2iq1IrKPmuua6vW0QVRlsK29Kg2jc',
    appId: '1:217418164159:web:d8b8968b9619600b08630a',
    messagingSenderId: '217418164159',
    projectId: 'quad-2c91f',
    authDomain: 'quad-2c91f.firebaseapp.com',
    storageBucket: 'quad-2c91f.firebasestorage.app',
    measurementId: 'G-XB96KRR790',
  );

}